### ISSUE TITLE
开源计划

### ISSUE THREAD

**Issue by Tracyxzh** [alicogintel/AliCoCo#1]
请问下开源的内容有哪些呀~

**Comment by angrymidiao** [comment]
> 请问下开源的内容有哪些呀~

我们计划稍后release 电商领域内1-2个行业的图谱数据，以及基于AliCoCo的一些task+实验用的dataset。因为涉及到数据安全等问题，开源的流程可能会相对较长，尽情关注~

**Comment by QwertyJack** [comment]
貌似快两年了

**Comment by lvfuyu** [comment]
> 嗯 这人一年多前离职了 没人管这事了

**Comment by guotong1988** [comment]
mark
